spring.application.name=backend


spring.datasource.url=jdbc:postgresql://db.dckzghjwdibseemluukq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=yunanoa1002

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080